name: celfdrive-macos
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - h5py
  - matplotlib
  - scikit-image
  - pillow
  - seaborn
  - tqdm
  - pyyaml
  - pytest
  - pip:
      - dill==0.3.8
      - opencv-contrib-python
      - networkx==3.2.1
      - tifffile==2024.2.12
      - imageio==2.34.0
      - fsspec==2024.2.0
      - openpyxl
      - pyarrow
      - torch
      - torchvision
      - torchaudio
      - ultralytics
      - sahi
      - jupyter
